const bots = []
const testers=[]
const scopes=[['单聊消息','C2C_MESSAGE_CREATE',false],['群聊 @ 消息','GROUP_AT_MESSAGE_CREATE',false],['频道 @ 消息','AT_MESSAGE_CREATE',false],['频道私信','DIRECT_MESSAGE_CREATE',false],['按钮交互','INTERACTION_CREATE',false],['机器人加入群聊','GROUP_ADD_ROBOT',false]]
let selectedBot=null
function show(view){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById('view-'+view).classList.add('active');document.querySelectorAll('.nav-item[data-view]').forEach(n=>n.classList.toggle('active',n.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'})}
document.addEventListener('click',e=>{const t=e.target.closest('[data-view]');if(t){e.preventDefault();show(t.dataset.view)}})
function renderBots(){const grid=document.getElementById('botGrid');if(!bots.length){grid.innerHTML='<div class="empty-state">暂无机器人</div>';return}grid.innerHTML=bots.map((b,i)=>`<article class="bot-card" data-index="${i}"><div class="bot-head"><div class="bot-avatar" style="background:${b.color}">BOT</div><div class="bot-main"><div class="bot-name-line"><span class="bot-name">${b.name}</span><span class="role">管理员</span></div><div class="bot-status"><i class="${b.status}"></i>${b.label}</div></div><span class="arrow">›</span></div><div class="bot-foot"><span class="mono">AppID ${b.id}</span><span>今天</span></div></article>`).join('');document.querySelectorAll('.bot-card').forEach(c=>c.onclick=()=>openBot(Number(c.dataset.index)))}
function openBot(i){selectedBot=bots[i];document.getElementById('manageName').textContent=selectedBot.name;document.getElementById('manageId').textContent='AppID '+selectedBot.id;document.getElementById('manageAppId').textContent=selectedBot.id;document.getElementById('botNameInput').value=selectedBot.name;document.getElementById('botDescInput').value=selectedBot.desc;show('manage')}
function renderEvents(){document.getElementById('eventGrid').innerHTML=scopes.map((s,i)=>`<label class="event-option ${s[2]?'active':''}"><input type="checkbox" data-index="${i}" ${s[2]?'checked':''}><span><b>${s[0]}</b><code>${s[1]}</code></span></label>`).join('');document.querySelectorAll('.event-option input').forEach(i=>i.onchange=()=>{scopes[i.dataset.index][2]=i.checked;i.closest('.event-option').classList.toggle('active',i.checked)})}
function renderTesters(filter=''){const list=document.getElementById('testerList');const rows=testers.filter(t=>(t.name+t.id).includes(filter));if(!rows.length){list.innerHTML='<div class="empty-state">暂无测试成员</div>';return}list.innerHTML=rows.map((t)=>`<div class="tester-row"><div class="tester-avatar" style="background:${t.color}">${t.name.slice(-1)}</div><div class="tester-main"><b>${t.name}</b><span class="mono">QQ ${t.id}</span></div><span class="type">${t.type}</span><button class="remove" data-id="${t.id}">移除</button></div>`).join('');document.querySelectorAll('.remove').forEach(b=>b.onclick=()=>{const i=testers.findIndex(t=>t.id===b.dataset.id);testers.splice(i,1);renderTesters(document.getElementById('testerSearch').value);toast('已移除')})}
function toast(text){const el=document.getElementById('toast');el.textContent=text;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),1500)}
document.getElementById('saveBot').onclick=()=>{if(!selectedBot){toast('暂无机器人可保存');return}selectedBot.name=document.getElementById('botNameInput').value.trim()||selectedBot.name;selectedBot.desc=document.getElementById('botDescInput').value;document.getElementById('manageName').textContent=selectedBot.name;renderBots();toast('机器人信息已保存到预览状态')}
document.querySelector('.copy').onclick=async()=>{if(!selectedBot){toast('暂无 AppID');return}try{await navigator.clipboard.writeText(selectedBot.id);toast('AppID 已复制')}catch{toast('当前浏览器不允许复制')}}
document.getElementById('saveEvents').onclick=()=>toast('事件配置已保存到预览状态')
document.getElementById('testerSearch').oninput=e=>renderTesters(e.target.value)
document.getElementById('sendRequest').onclick=()=>{const method=document.getElementById('method').value,path=document.getElementById('path').value;document.getElementById('response').textContent=JSON.stringify({preview:true,message:'独立预览不会发送真实请求',request:{method,path},next:'启动 FastAPI 后端并在 Vue 版本中配置凭证'},null,2)}
renderBots();renderEvents();renderTesters()
